FROM neural-style-api-base

# used in python scripts to detect if the python script is running inside the docker container
ENV RUNS_INSIDE_CONTAINER Yes

ARG NODE_VERSION=16.14.0
ARG NODE_PACKAGE_AMD64=node-v$NODE_VERSION-linux-x64
ARG NODE_HOME_AMD64=/opt/$NODE_PACKAGE_AMD64

ENV NODE_PATH $NODE_HOME_AMD64/lib/node_modules
ENV PATH $NODE_HOME_AMD64/bin:$PATH

RUN curl https://nodejs.org/dist/v$NODE_VERSION/$NODE_PACKAGE_AMD64.tar.gz | tar -xzC /opt/

RUN conda init bash
RUN conda update -n base conda
RUN conda install pytorch torchvision -c pytorch

# workaround for ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/opt/conda/lib/python3.9/site-packages/PIL/__init__.py)
# change PILLOW_VERSION to __version__
RUN sed -i 's/from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION/from PIL import Image, ImageOps, ImageEnhance, __version__/g' /opt/conda/lib/python3.9/site-packages/torchvision/transforms/functional.py

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install

# Bundle app source
COPY . .

RUN cd script && python3 models/download_models.py

# nodejs server is listening on this port
EXPOSE 3000

CMD [ "node", "server.js" ]
